spring.datasource.url=jdbc:mysql://localhost:3306/car_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
server.servlet.context-path=/api

jwt.secret=mysecretkey123456789


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=syedsalah2405@gmail.com
spring.mail.password=hisx nyub sgfl rrrw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true